# Generated by Django 4.1.3 on 2023-02-13 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('V', 'Vegetables'), ('SH', 'Spices and Herbs'), ('CP', 'Cereals and Pulses'), ('M', 'Meat'), ('D', 'Dairy Products'), ('F', 'Fruits'), ('S', 'Seafood'), ('SP', 'Sugar and Sugar Produts<')], max_length=2)),
                ('owner', models.ManyToManyField(related_name='ingredients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
