# Generated by Django 4.1.3 on 2023-02-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_remove_ingredient_owner_ingredient_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(max_length=7),
        ),
    ]
