# Generated by Django 4.1.3 on 2023-02-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('type', models.CharField(max_length=20)),
                ('serv', models.IntegerField()),
                ('inst', models.TextField()),
                ('ingredients', models.ManyToManyField(blank=True, related_name='recipes', to='cookbook.ingredient')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
